language: python
python: 
  - 2.7
install: 
  - git clone https://github.com/Gab-km/konira_portable konira
  - cd ./konira
  - python ./setup.py install
  - cd ..
script:
  - cd test
  - konira
notifications:
  on_success: always
